### ISSUE TITLE
Problem: clamav socket parent folder problems in centos

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/am-packbuild#102]
In centos 7, with selinux enabled, and /var/run pointing to /run (a tmpfs mount), archivematica doesn't work after a server reboot, because the parent folder for the clamav socket doesn't allow others to read it:

<pre>
drwx--x---. 2 clamscan clamscan 60 Dec  5 10:35 /var/run/clamd.scan
srw-rw-rw-. 1 clamscan clamscan 0 Dec  5 10:35 /var/run/clamd.scan/clamd.sock
</pre>

This folder is created with each reboot, in /lib/tmpfiles.d/clamd.scan.conf , so we should add our own config file in /etc/tmpfiles.d/ in order to override the default permissions.

**Comment by sevein** [comment]
@scollazo if this is going to be hard to solve talk to @ross-spencer because he's working on a new PR where you should be able to manually choose the backend and default to `clamscan` which doesn't rely on clamd. Not ideal maybe because clamd can be faster but perhaps a compromise due our time constraints for the AM17 release.

**Comment by scollazo** [comment]
It's not difficult to solve, we only need to put a file with the following content:

<pre>
d /var/run/clamd.scan 0775 clamscan clamscan
</pre>

In /etc/tmpfiles/archivematica-clamd.conf (example name)

**Comment by scollazo** [comment]
As we now use a tcp socket, I'm closing this
