### ISSUE TITLE
Add sample configuration file

### ISSUE THREAD

**Issue by scollazo** [artefactual-labs/am-packbuild#53]
Add a template file with all availabe configuration variables in form of environment vars into /usr/share/doc/archivematica-<package>

**Comment by sevein** [comment]
@scollazo would you consider not doing this at all? i.e. close the issue. I'm saying this because I believe your template will become obsolete as soon as soon as we add more environment strings.

What I think we should do is to point the user to the document where the configuration system is detailed. There is not a place yet for this but I don't think our packages should carry that responsibility.

**Comment by sevein** [comment]
It's planned to add to Dashboard/MCPServer/MCPClient/StorageService repos a file listing all the environment variables supported and their corresponding INI settings and also describing if they're mandatory or optional. Wouldn't that be enough? In archivematica-docs we can explain how to use them depending if you are using trusty/xenial/centos on a package-based installation.

**Comment by scollazo** [comment]
As artefactual/archivematica#845 has been merged , I'm closing this.
