### ISSUE TITLE
Problem: deb pkgs don't install pip requirements properly

### ISSUE THREAD

**Issue by sevein** [artefactual-labs/am-packbuild#69]
@scollazo is aware of this problem but I realize no issue has been submitted yet.

Our deb packages are using virtualenvs (yay!) but unlike rpms/ansible/docker they're not installing all the pip requirements as listed below. This seems to be a challenge but I still don't quite understand yet the reason - I hope @scollazo can add a comment with more details.

The approach of patching the requirements feels wrong, e.g. see [debs/trusty/archivematica/debian-MCPClient/patches/mcp-client-extra-requirements.diff](https://github.com/artefactual-labs/am-packbuild/blob/master/debs/trusty/archivematica/debian-MCPClient/patches/mcp-client-extra-requirements.diff) or [debs/xenial/archivematica/debian-MCPClient/patches/mcp-client-extra-requirements.diff](https://github.com/artefactual-labs/am-packbuild/blob/master/debs/xenial/archivematica/debian-MCPClient/patches/mcp-client-extra-requirements.diff). These files are going to become obsolete as soon as the requirements changes in upstream. Also there are missing dependencies, e.g. agentarchives is not included in that diff and many more. They're maybe not always needed but some workflows will surely break, e.g. MCPClient has a client script used to upload to different access systems. This client script depends on `agentarchives`.

---

#### MCPClient

```
pip install -r src/archivematicaCommon/requirements/production.txt
pip install -r src/dashboard/src/requirements/production.txt
pip install -r src/MCPClient/requirements/production.txt
```

#### MCPServer

```
pip install -r src/archivematicaCommon/requirements/production.txt
pip install -r src/dashboard/src/requirements/production.txt
pip install -r src/MCPServer/requirements/production.txt
```

#### Dashboard

```
pip install -r src/archivematicaCommon/requirements/production.txt
pip install -r src/dashboard/src/requirements/production.txt
```

**Comment by scollazo** [comment]
Debian packages are made using dh_virtualenv, and installing more than one requirements might be challengin. Also, in debian packaging, using files from outside the root package folder is not a good practice.

I tried to avoid the cargo cult, and patched mcpclient with the needed dependencies, but I'll follow your suggestion to add all the requirements from common and dashboard

We should address this issue in the archivematica mcpclient repo, listing in its requirements all the pip packages needed, instead of borrowing from others.
